### ISSUE TITLE
Interview Prep Resources

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#11]
### Overview
Team to review the design-thinking & interviewing resources (IDEO & others) in preparation for the interviews:

- Frame your challenge: http://www.designkit.org/methods/60
- Secondary Research: http://www.designkit.org/methods/21
- Interview: http://www.designkit.org/methods/2
- Expert Interview: http://www.designkit.org/methods/43
- UX Checklist! https://uxchecklist.github.io/

### Instructions
If you're interested in conducting interviews, add a comment below indicating you've reviewed the above material and tag @awadethomas.

**Comment by awadethomas** [comment]
**Tossing in a few more great UX Resources**
- NN on interviewing users: https://www.nngroup.com/articles/interviewing-users/
- NN on field studies: https://www.nngroup.com/articles/field-studies/?lm=interviewing-users&pt=article
- Usability.gov on contextual interviews: https://www.usability.gov/how-to-and-tools/methods/contextual-interview.html
