### ISSUE TITLE
Follow-up w/ LA Housing 6-18-2019

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#12]
### Overview
Waiting on feedback from several LAFH stakeholders.

### Action Items
- [x] Follow-up w/ Dan Parziale, Director of Housing Services, to 1) get connected w/ specific stakeholders to interview, 2) obtain an existing org chart, and 3) inquire re: LA Family Housing Open House Event on July 10th
- [x] Reach out to Jon Deutsch, Housing Location Coordinator, to schedule an interview with Jon & others on the Housing Location Team
- [x] Reach out to Kris Freed, Chief Programs Officer, and ask Kris to introduce us to specific stakeholders to interview

**Comment by Martyna-S** [comment]
This is closed. Aaron & I coordinated with Dan, Kris and Jon via emails and have all the contacts we need to schedule additional interviews.
