### ISSUE TITLE
Immersive Research - Stabilization Team

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#121]
### Overview
Need to do some observational research at the LAFH offices of the Stabilization team in action. Would be good to find a day when a few of us can get up to N. Hollywood and split up to sit in with a few teams.

### Nota Bene!
Be sure to get an example of / ask about the **client survey questionnaire** (from #58)

### Resources
http://www.designkit.org/methods/23

**Comment by awadethomas** [comment]
@Martyna-S and Dom, let's link to your notes that you took when you were on site here

**Comment by awadethomas** [comment]
I found Martyna's and Dom's notes--I am adding all current resources/insights below and closing

- Interview Insights from Kasia Hernas - Stabilization Manager : https://docs.google.com/document/d/1u0l1sUWtewOaDukBCFZUCc04QZGIG9R5_V-Jzkm1rH0/edit?usp=sharing
- Interview Insights from Katheryn & Cheryl: https://docs.google.com/document/d/1zEvCwsn_3ztrg6dizr80Oh7tJFbbuHH7JD9VxQPNQIc/edit?usp=sharing
- Shadowing Insights from Martyna & Dom: https://docs.google.com/document/d/1VendQsveSkNwBGdntau-a1lZttv8GGmP9Qls8YKUZRo/edit?usp=sharing
