### ISSUE TITLE
Immersive Research - Navigation

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#122]
### Overview
Need to do some observational research at the LAFH offices of the Navigation team in action. Would be good to find a day when a few of us can get up to N. Hollywood and split up to sit in with a few teams.

### Resources
http://www.designkit.org/methods/23

**Comment by AlexChh93** [comment]
Job Shadowing Recap:

https://docs.google.com/document/d/1uZ5Ouny9NhalrUUe9K8YvCxtRH36VV_VmZdWHo4eE1M/edit?usp=sharing

**Comment by awadethomas** [comment]
All interview info and documentation from Tia here:
https://drive.google.com/drive/folders/1iUoHbicIbkcXwVFpEV1MyKMYdWUM0UTa?usp=sharing

**Comment by awadethomas** [comment]
Wrapping this task up, since we added our shadowing and
