### ISSUE TITLE
Improved documentation solution

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#13]
### Overview
Currently the project is using a shared Drive folder, which is owned by CfA. Regular contribs don't have access to this folder and need to go through H4LA admins in order to archive artifacts like meeting notes, discovery documentation, etc.

### Action Items
- [ ] Research alternatives

### Resources/Instructions
_PENDING_

**Comment by ExperimentsInHonesty** [comment]
I am grateful for your patience while we work this out.

I have created a report and sent it Nina. Unfortunately both Nina (Hack for LA's co-captain) and Tom Dooner (CfA) are on vacation. However, while we wait for them to come back we have a working solution.

On the index of files document there are some blank documents and sheets at the bottom and they are already pre-shared with anyone who is given the link. So all you have to do to create new documents is to open one of those, and then rename it and add it to the index with its new descriptive name. I will create some new blanks.

**Comment by owenjoseph** [comment]
@ExperimentsInHonesty created a shared folder in the CfA drive that our project leadership has edit access to: 

https://drive.google.com/drive/folders/1sZFAf9_7fw7AiKo7rWjB7s6SwcALPeJt?usp=sharing (restricted access)
