### ISSUE TITLE
Review Centrality-based in Group Recommender Systems Algorithm Research

### ISSUE THREAD

**Issue by Rankazze** [hackforla/shared-housing#138]
### Action Items
1. Review research.
2. Be prepared to discuss.

### Resources/Instructions
https://drive.google.com/open?id=1hvwa5BLX89wInMS2f04uhEhNd4sDRebN

**Comment by tylerthome** [comment]
The data structures described in this paper were determined to be very well-suited to our problem. The proposed algorithm will not be used as presented, but some of the core components in the pipeline leading to the matching algorithm will be used
