### ISSUE TITLE
Schedule open house w/ Jonathan Deutsch

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#14]
### Overview
The open house is where clients are given the opportunity to see a potential property in person, and also where they are given documents for and guided through the application process. It's also an opportunity for navigators and (optionally) landlords to observe client group dynamics.

We need a small group (no more than three) willing to attend an open house.

**NB: Open houses happen during normal working hours (M - F, 9a - 5p)**

### Action Items
- [x] schedule a date w/ Jonathan Deutsch (Location Team)
- [x] Jon mentioned potentially needing some training / waiver signing before attending? Confirm this.
- [x] identify 2 - 3 volunteers to attend open house
- [x] create / source observation guidelines document

### Resources/Instructions
_PENDING_

**Comment by awadethomas** [comment]
We should treat this as a field study!

**Comment by owenjoseph** [comment]
Hey @awadethomas I'm going to assign this to you, since I gather you're taking over as point of contact while @Martyna-S is traveling

If you have any resources for conducting field research, please add links to the issue description under the **Resources** section.

Thanks!

**Comment by owenjoseph** [comment]
Last comment from Jon D on July 16: "we are very close to setting a date for our open house."

Follow up if we don't hear back by EoD Monday?

**Comment by awadethomas** [comment]
Last activity on this is Jon saying that this month's open house was cancelled and we will have to connect with him next month (presumably August)

**Comment by Martyna-S** [comment]
Hi! Do we know why it was cancelled? Maybe this would be a good insight into their process / potential improvement recommendations
