### ISSUE TITLE
Schedule LAFH office shadowing

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#15]
### Overview
Observe LAFH location, navigation, and stability teams on site at LAFH housing offices in North Hollywood.

**NB: Need to schedule this during working hours (M - F; 9a - 5p)**

### Action Items
- [x] Identify 2 - 3 team members
- [x] identify who at LAFH we're going to shadow
- [x] schedule day for shadowing
- [ ] disseminate ideo immersion methods (below)

### Resources/Instructions
https://lafh.org/
7843 Lankershim Blvd, North Hollywood, CA 91605

http://www.designkit.org/methods/23 (Immersion methods)

**Comment by awadethomas** [comment]
Another good example of how to hold a field study: https://www.nngroup.com/articles/field-studies/
