### ISSUE TITLE
Consolidate follow-up Qs for Jonathan Deutsch

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#17]
### Overview
We met with Jon on June 25, 2019, for a little over an hour. We should send him any follow-ups we have in a timely manner, while they are fresh.

### Action Items
- [x] create shared document for collecting questions
- [x] link to transcription of interview (contribs should review this first)
- [x] solicit Qs from team
- [ ] send Qs to Jon D

### Resources/Instructions
https://docs.google.com/document/d/1TXrUQNCUwPdC8MdK4X7o4YSU__qDpe49F4oPInD-mg0/edit?usp=sharing

**Comment by awadethomas** [comment]
I am not sure the best place to add these, but find my high-level notes of the Jon interview below 
[Jon.Meeting.Insights-7.7.2019.pdf](https://github.com/hackforla/shared-housing/files/3366048/Jon.Meeting.Insights-7.7.2019.pdf)

**Comment by awadethomas** [comment]
@owenjoseph & @Martyna-S do we need to ask Jon anything else for now? - All of my key questions were answered as far as the process. If anything, we might want to ask Jon some persona-building questions.

**Comment by owenjoseph** [comment]
@awadethomas I'm going to close this out since we're not receiving any more feedback and the humanizing questions are ostensibly covered by #10
