### ISSUE TITLE
Add user journeys to staging site

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#172]
### Overview 
Add Nav, Outreach, Stabilization, and Tenant user journey images to site. Please see attached first drafts from Miro.

Resources/Instructions
For now these can be simple images users can scroll through.
Both images and how/where we display them will change later (e.g. drop down menu). Let's just get them on the site for now.

![Outreach User Journey 11 2](https://user-images.githubusercontent.com/24849648/68075617-63d6ef80-fd67-11e9-8543-64a1eb025e61.PNG)

![Stabilization User Journey 11 2](https://user-images.githubusercontent.com/24849648/68075621-6df8ee00-fd67-11e9-9cdf-4f458221bb54.PNG)

![Nav User Journey 10 31](https://user-images.githubusercontent.com/24849648/68075413-be228100-fd64-11e9-85f7-5c9bc427e4a5.png)

![Tenant User Journey 11 2](https://user-images.githubusercontent.com/24849648/68075622-751ffc00-fd67-11e9-833f-5357f906cac1.PNG)

**Comment by itsevalieu** [comment]
@kkchu791  these are the user journey maps for the landing page
