### ISSUE TITLE
Review DTLA Project Manager Responsibilities doc from Bonnie

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#18]
### Overview
From @ExperimentsInHonesty:

> Hi Shared housing peeps!  Here is the document I promised to deliver to whoever is the project manager on your project (I don't know who that is, which is why this is going to the whole channel). https://docs.google.com/document/d/1lmQXW_4KOC3HDGdA0-wgEqDJlROYdKzDslK2wrDLJbQ - please comment freely on the document or reach out directly to me if you don't want to comment publicly.  Your team is one of the first to see this, so I am sure it will require revisions and improvements.

### Signoff
- [x] @owenjoseph 
- [ ] @abregorivas 
- [x] @Martyna-S

**Comment by owenjoseph** [comment]
@abregorivas I was reviewing this point in Bonnie's document:

> Documentation management - It’s important that we make all our projects inclusive.  Making sure that all new team members or potential team members can easily navigate instructions for how to participate both in person and remotely is key to making that a reality.  

I wonder if GitHub is the best place for document archiving, given the Browser UI file size limits and challenges I've seen other contributors encounter, especially designers and product folks who are not necessarily fluent in Git.

I don't know if we'll have time to discuss this tonight but I wonder if there's a more self-service solution to this than you having to act as archivist for the team.

**Comment by abregorivas** [comment]
Let's discuss on the week of the 9th.

**Comment by owenjoseph** [comment]
@abregorivas I'm going to close this one out - already got another task to track coming up with a documentation solution.

**Comment by ExperimentsInHonesty** [comment]
I am grateful for your patience while we work this out.

I have created a [report](https://docs.google.com/document/d/1fDjXEggSzGJGWsO5--XYyGoVvvwbF2lIxB1jpUqzNEc) and sent it Nina.  Unfortunately both Nina (Hack for LA's co-captain) and Tom Dooner (CfA) are on vacation.  However, while we wait for them to come back we have a working solution.

On the [index](https://drive.google.com/drive/u/0/folders/1sZFAf9_7fw7AiKo7rWjB7s6SwcALPeJt) of files document there are some blank documents and sheets at the bottom and they are already pre-shared with anyone who is given the link.  So all you have to do to create new documents is to open one of those, and then rename it and add it to the index with its new descriptive name.  I will create some new blanks.
