### ISSUE TITLE
Create a service blueprint of the current shared housing process

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#187]
### Overview
Let's create a service blueprint diagram of the current LAFH Shared Housing process so current and new HfLA team members can understand it quickly and better. 

### Action Items
Create a service blueprint diagram of how we understand the LAFH Shared Housing process works. 

This should be a simple image (e.g. a PNG, not stored in Miro) so that it can be easily used and referenced by the whole Shared Housing team. 

### Resources/Instructions
Wikipedia page on service blueprints: https://en.wikipedia.org/wiki/Service_blueprint 
Another service blueprint description from NN Group: https://www.nngroup.com/articles/service-blueprints-definition/

**Comment by awadethomas** [comment]
Current Progress on blueprint
[Blueprint.pdf](https://github.com/hackforla/shared-housing/files/3935435/Blueprint.pdf)

Next steps are to beautify this design to make it easier to digest and include added variables like time and arrows to show vertical flow

**Comment by awadethomas** [comment]
I worked through and created a better designed service map/blueprint! You can access this doc in Miro for feedback 
- @Rankazze I recommend checking it out to make sure it makes sense. Feel free to use Miro to add comments where we have questions.

[Service Map-Blueprint](https://user-images.githubusercontent.com/11351652/71424432-4b3bd500-2646-11ea-90fa-6f88721139e7.jpg)

**Comment by ExperimentsInHonesty** [comment]
@awadethomas What is the reason for having the miro version and this version https://drive.google.com/file/d/1gzP807JUUWUoBOJU2Yz6fz-9DhDSqSuX/view
?  They are the same no?  Which is the one you want the client to see?

**Comment by awadethomas** [comment]
Hey @ExperimentsInHonesty, 

It would be best for the client to see the Miro version!

**Background**
The Miro document I last provided is the latest version. I created it in a way I thought was easier to read and understand, including arrows. Miro also allows for us to make changes really easily as we might learn more.
