### ISSUE TITLE
Onboarding documentation for new folks

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#19]
### Overview
Roland has already done a lot of this work on the README. Is there anything else we can add to help new folks onboard and orient?

### Action Items
PENDING

### Resources/Instructions
PENDING

**Comment by Martyna-S** [comment]
Yes, I created a project overview PPT (posted on Slack & Google Drive), that I'd like to review with the team tonight if we have the time

**Comment by awadethomas** [comment]
At some point, we'll need to create a design artifact repo, or at least folder

**Comment by Martyna-S** [comment]
I finalized the PPT based on the comments from the team. It's ready to be shared as new folks come in & join the team.
