### ISSUE TITLE
Transcribe audio from interview w/ Jon Deutsch

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#20]
### Overview
Same thing we did with Dan's interview - use a 3rd party service to transcribe audio from Jon's interview.

### Action Items
Does @awadethomas have this recording on his phone?

### Resources/Instructions
PENDING

**Comment by awadethomas** [comment]
Adding the transcription to this - thanks for transcribing Jose!
[Jonathan - June 25.pdf](https://github.com/hackforla/shared-housing/files/3351100/Jonathan.-.June.25.pdf)

**Comment by owenjoseph** [comment]
Added interview assets to github (https://github.com/hackforla/shared-housing/tree/master/References/Interviews/Audio)

**Comment by awadethomas** [comment]
@owenjoseph can we add the following doc as well? 
[Jon.Meeting.Insights-7.7.2019.pdf](https://github.com/hackforla/shared-housing/files/3366056/Jon.Meeting.Insights-7.7.2019.pdf)
