### ISSUE TITLE
Add agile manifesto and principles to landing page nav bar

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#201]
### Overview
Add links to the Home page, Agile Manifesto, and Agile Principles to the landing page's blue nav bar. 

### Action Items
On our landing page [site](http://smileapp.ivan-alpha.xyz/):

1) Add an "Agile Manifesto" link to the blue nav bar and link it [here](https://drive.google.com/open?id=1HnV2mu2bZlhB83iqFHsV0PIk6ST7K4FQ)

2) Add an "Agile Principles" link to the blue nav bar and link it [here](https://drive.google.com/open?id=18FvfcqkWaN5yG2bQglt3kHa_i-w6GzzR)

3) Add a "Home" link to take users back to the main landing page, http://smileapp.ivan-alpha.xyz/

### Resources/Instructions
Landing page: http://smileapp.ivan-alpha.xyz/
Agile Manifesto: https://drive.google.com/open?id=1HnV2mu2bZlhB83iqFHsV0PIk6ST7K4FQ
Agile Principles: https://drive.google.com/open?id=18FvfcqkWaN5yG2bQglt3kHa_i-w6GzzR

**Comment by itsevalieu** [comment]
I'll take care of this.
