### ISSUE TITLE
Interview Training

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#21]
### Overview
In preparation for going on client interviews, we should think about doing some formalized training. This would be in addition to reviewing the materials that @awadethomas has been providing.

### Action Items
Schedule some time to do interview role-playing. Get feedback.

### Resources/Instructions
PENDING

**Comment by awadethomas** [comment]
Here's a great overview of role playing too: http://www.designkit.org/methods/36
- My key takeaway here is making it fun--maybe having something like a costume or prop to really bring the role playing of interviews to life

**Comment by awadethomas** [comment]
Adding another great resource for interviews. I especially recommend reading through what an interview will NOT tell you: https://www.nngroup.com/articles/interviewing-users/
