### ISSUE TITLE
Add functionality to the hamburger button

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#213]
Add functionality to the hamburger button for mobile responsiveness.

**Comment by wsbuck** [comment]
I'll pick this up.

**Comment by karlmageddon** [comment]
Is the hamburger button going to be present even when the screen size is enough to fit the entire nav bar with all the buttons?

**Comment by wsbuck** [comment]
@karlmageddon I'm not sure yet. It does seem like the nav bar is getting pretty cluttered with links so maybe there is a benefit of stashing some of them away. What do you think?

**Comment by karlmageddon** [comment]
The nav bar is getting cluttered but I'm pretty sure we can (and should) fold the Dashboard, Prototype-Form, and whatever Demo is housing under one big "Demos" section. That's probably a discussion for another ticket.

I'm not a fan of having a the hamburger icon up when it isn't needed. UX-wise it's redundant for a user to tap an icon and have it display links that are already displayed. I say that when the window hits a certain threshold the nav buttons should disappear and the hamburger icon should take its place.
