### ISSUE TITLE
One question one location prototype design phase

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/shared-housing#236]
### Overview
Create wireframe for one question one location prototype

### Action Items

- [x] Create mood board
- [x] Sketching mobile
- [x] Sketching web
- [x] Create wireframe in figma
- [x] Handoff to front end and Product

### Resources/Instructions
https://www.figma.com/file/SUrFxtWMxNz57mZlGeTiAD/SMILE-Demo?node-id=0%3A1

**Comment by awadethomas** [comment]
We presented the current version of the wireframes to front end tonite. Next steps are as follows...

- [ ] Refine Wireframes
- [ ] Create a Clickable Prototype

**Comment by awadethomas** [comment]
We completed what we initially set out to do, we will branch next steps into a new design task
