### ISSUE TITLE
Research implementing story points in GitHub

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#24]
### Overview
To help plan Sprints, the question was raised last week of whether or not GutHub supports story points. Let's spend a little time looking into this.

### Action Items

- [x] Research this
- [x] Invite others to add to this
- [ ] Collect findings here

#### Findings
GitHub doesn't support issue sizing out-of-the-box. A common workaround is using labels as story points, but calculating velocity because an annoyingly manual task involving google sheets and cut-and-paste.

Other options include Trello integration and GitHub plugins like ZenHub.

Collected articles:

- https://unito.io/blog/github-projects-agile/
- https://github.com/features/project-management/

**Comment by abregorivas** [comment]
We should consider using ZenHub.

**Comment by owenjoseph** [comment]
Looks like it's free for public repos. I'm going to make a new issue for implementing ZenHub – thanks @abregorivas 

https://app.zenhub.com/login
