### ISSUE TITLE
Update design onboarding information in the wiki

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#242]
### Overview
Update the Shared Housing wiki page with Design onboarding information.

### Action Items
In the Shared Housing Wiki [page](https://github.com/hackforla/shared-housing/wiki/UI-UX-Designer)
1. Review the HfLA Website team's Design onboarding [page](https://github.com/hackforla/website/wiki/UI-UX-Designer) 
2. Fill in with the information relevant to the Shared Housing project
3. Add anything else that's essential for new Design team members to know

### Resources/Instructions
HfLA website Design onboarding [page](https://github.com/hackforla/website/wiki/UI-UX-Designer)
Shared Housing Wiki PM [page](https://github.com/hackforla/shared-housing/wiki/Project-Manager)

Target page: Shared Housing Wiki Dev [page](https://github.com/hackforla/shared-housing/wiki/UI-UX-Designer)

**Comment by awadethomas** [comment]
Thinking through this, let's add

- New Person Deck
- UX Process Diagram/Image
- Miro Board
- Github Board

**Comment by awadethomas** [comment]
We should be set here!
