### ISSUE TITLE
Assign open issues located in "Issues to update" column to relevant team member

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/shared-housing#248]
### Overview
Lots of user research has been done and needs to be documented on the relevant open issue. 

### Action Items

- [x] Review open issues and assign person who did the research to their issue:
   - [x] #121   
   - [x] #122 
   - [x] #123 
   - [x] #124  
   - [x] #38 
- [x] Ask the team members to Update the Epic,  called Immersive Research,  as they complete the connecting of their documentation to the open issues above.  #119

**Comment by awadethomas** [comment]
Assigned out, added comments and added to our prioritized backlog to make sure this gets done quickly
