### ISSUE TITLE
Come up with list of labels for Project Board

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#25]
### Overview
A number of tissue tagging needs have already been identified, including:
- internal tasks (like market research, project infrastructure setup, design tasks)
- external tasks (like outreach, user research, partner scheduling)

And GH projects instantiate with this default label set:

- bug
  - Something isn't working
- duplicate
  - This issue or pull request already exists
- enhancement
  - New feature or request
- good first issue
   - Good for newcomers
- help wanted
  - Extra attention is needed
- invalid
  - This doesn't seem right 
- question
  - Further information is requested
- wontfix
  - This will not be worked on

### Action Items
I think it makes sense to devote a little time to brainstorming additional labels as a team next week

### Resources/Instructions
_We can detail our label library here_

**Comment by abregorivas** [comment]
I recommend creating label categories such as "status labels", "type labels" and "priority labels"
examples Label names
[ ] - Status: inProgress
[ ] - Status: pendingReview
[ ] - Type: bug
[ ] - Type: enhancement
[ ] - Priority: low
[ ] - Priority: urgent

**Comment by dtruong8** [comment]
adding on top of what Roland is saying
[] - Status: testing
[] - Status: blocked
[] - Priority: medium

**Comment by owenjoseph** [comment]
Closed, as this will be something we review on an ongoing basis.

**Comment by owenjoseph** [comment]
And also because dev has added the labels they need :)
