### ISSUE TITLE
Put Roland in touch with Kenneth (matching algorithm)

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#28]
@Roland - Kenneth (who attends the DTLA pretty regularly) said he had a matching algorithm he'd been working on a year or two back, and seemed interest in speaking with you about it.

Do you know him / have his contact info?

**Comment by abregorivas** [comment]
@owenjoseph I don't know him but would love to speak with him. Hopefully he is there on Tuesday.
