### ISSUE TITLE
Create TenantList React Component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#280]
Overview
Create a list of TenantListItem components. Should take in an array of Tenants as a prop and then render and return the list of TenantListItems.

Action Items
- [ ] Array of Tenant objects to pass as TenantListItem props
- [ ] Use material-ui
- [ ] Add to storybook

Resources

[Tenants Wireframe](https://www.figma.com/file/SUrFxtWMxNz57mZlGeTiAD/SMILE-Demo?node-id=26%3A3610)
![image](https://user-images.githubusercontent.com/20483664/71052482-4fc13480-2100-11ea-93ac-45d90f3cc330.png)

#268 #281

**Comment by kennethlee** [comment]
I'll work on this one.
