### ISSUE TITLE
Create TenantListItem React Component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#281]
### Overview
Create TenantListItem React component for Tenant list view. Should take in props with tenant details outlined below. Should follow wireframe listed in resources below: Tenants.

### Action Items
- [ ] Take in tenant name, handicap accessible, etc props
- [ ] Use material-ui
- [ ] Add to storybook

### Resources/Instructions
[Tenants Wireframe](https://www.figma.com/file/SUrFxtWMxNz57mZlGeTiAD/SMILE-Demo?node-id=26%3A3610)

![image](https://user-images.githubusercontent.com/20483664/71054181-de848000-2105-11ea-8ea8-536593f8333e.png)

#268 #280

**Comment by kennethlee** [comment]
I got this.
