### ISSUE TITLE
Interview reps from Navigation, Stabilization, and Outreach teams

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#29]
### Overview
We've met with Jon Deutsch (Location team); we should conduct similar interviews with a rep each from the LAFH Navigation and Stabilization teams.

### Action Items
- [x] ID rep(s) from Navigation team
- [x] ID rep(s) from Stabilization team
- [x] ID rep(s) from Outreach team
- [x] schedule interview with Navigation team rep
- [x] schedule interview with Stabilization team rep
- [x] schedule interview with Outreach team rep
- [x] archive Navigation Team interview artifacts
- [x] archive Stabilization Team interview artifacts
- [x] archive Outreach Team interview artifacts

### Resources / instructions
Add links to archived interview artifacts here when done:

LAFH Contacts list and Interview Schedule: https://drive.google.com/open?id=13OfiSA57NGTF6dA9T3ErmXT3aNE3GYINY9dJ_3yYRLY

Interview artifacts folder on Drive: https://drive.google.com/open?id=1vqR5xfPRvVpvk-fzNzGrjvKRwuR6BNOP

**Comment by owenjoseph** [comment]
From email chain with @Martyna-S / @awadethomas and LAFH personnel:

**Stabilization Team:**
Cheryl Castillo (CCastillo@lafh.org)
Katheryn Hayward (Khayward@lafh.org)
Kimberly Roberts (KRoberts@lafh.org)

**Comment by owenjoseph** [comment]
**Navigation Team:**
Tia Dickson (TDickson@lafh.org)

**Outreach Team:**
Elyssa Rosen (ERosen@lafh.org)
Alynn Gausvic (AGausvik@lafh.org)

**Comment by Martyna-S** [comment]
@awadethomas Hi Aaron! Hope it's okay: I've assigned your name to this task since I'll be away / traveling in Europe starting this Friday through beginning of August. I sent the initial emails & follow-ups just last week (which I cc'd you & Owen on) so it's a matter of following-up and trying to reach the remaining teams: Housing Navigation Team (Tia) and Outreach & Engagement Team (Elyssa & Alynn).

**Comment by owenjoseph** [comment]
Outreach team has confirmed they can come in for an interview on July 30th.

**Comment by owenjoseph** [comment]
Navigation interview happening this coming week, Tuesday, July 23rd.

Time: 7:00
Location: LaKretz (DTLA Hacknight)
Interviewers: @awadethomas @jlopez08 @maryamhabibi
Interviewee: Tia Dickson

**Comment by owenjoseph** [comment]
Outreach interview happening this coming week, Tuesday, July 23rd.

Time: 7:00
Location: LaKretz (DTLA Hacknight)
Interviewers: @jlopez08 @philippe101 (one more pending)
Interviewees: Elyssa Rosen, Alynn Gausvic
