### ISSUE TITLE
Competitive Research - research and presentation

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#4]
### Overview
Perform "competitive"* research - what others are doing to solve the issue?

### Action Items
- [x] Collect all research previously shared on slack in one centralized location
- [ ] Pick date to present research at hack night
- [ ] Presentation

### Resources
Shared so far on slack: 
- https://ridley-thomas.lacounty.gov/index.php/homeless-crisis-3/
- https://ridley-thomas.lacounty.gov/index.php/ordinance-against-housing-discrimination/
- https://www.marketplace.org/2019/02/21/los-angeles-homeless-advocates-have-new-tech-tool-affordable-housing/
- https://link.medium.com/uuE6PvnIDX
- http://www.leaseuplosangeles.org/

**Comment by owenjoseph** [comment]
@philippe101 I collected some of the resources you and others had shared in slack. Please feel free to remove anything you think isn't appropriately labeled "competitive research" and add anything else you've found. Cheers!

**Comment by owenjoseph** [comment]
Adding some clippings shared by Sebastian in slack:

"A few clips from articles with information about what some other cities are doing about finding housing for homeless. Also a few clips citing Housing First, a group that offers housing for homeless regardless of mental health or addiction with few living rules or restrictions. Mental health and rehab services are offered, but not required. Also a few stats of LA's homeless situation and how we are finding them permanent housing.

Not sure if any of this info can contribute directly to the project but it's at the very least relevant and interesting. May spark some good ideas"

![SmartSelect_20190612-085630_Chrome](https://user-images.githubusercontent.com/39287217/59992811-72b3d580-9602-11e9-99b4-de5fa33b2dde.jpg)
![SmartSelect_20190612-085057_Chrome](https://user-images.githubusercontent.com/39287217/59992812-72b3d580-9602-11e9-9137-ae7b1b7ea968.jpg)
![SmartSelect_20190612-084920_Chrome](https://user-images.githubusercontent.com/39287217/59992813-72b3d580-9602-11e9-8168-bd253b2014f9.jpg)
![SmartSelect_20190612-084551_Chrome](https://user-images.githubusercontent.com/39287217/59992814-72b3d580-9602-11e9-8abd-94b7f1f1d5a2.jpg)
![SmartSelect_20190612-084237_Chrome](https://user-images.githubusercontent.com/39287217/59992815-72b3d580-9602-11e9-9912-224fdb764a30.jpg)
![SmartSelect_20190612-083515_Chrome](https://user-images.githubusercontent.com/39287217/59992816-734c6c00-9602-11e9-9023-8d4b85d6d150.jpg)
![SmartSelect_20190612-083224_Chrome](https://user-images.githubusercontent.com/39287217/59992817-734c6c00-9602-11e9-98f4-e717f03b5778.jpg)
![SmartSelect_20190611-235939_Chrome](https://user-images.githubusercontent.com/39287217/59992818-734c6c00-9602-11e9-86d8-ac68a5a2e665.jpg)
![SmartSelect_20190611-235617_Chrome](https://user-images.githubusercontent.com/39287217/59992819-734c6c00-9602-11e9-9fbb-6c9e03329d86.jpg)
![SmartSelect_20190611-232917_Chrome](https://user-images.githubusercontent.com/39287217/59992820-734c6c00-9602-11e9-90bf-061118af5d48.jpg)

**Comment by owenjoseph** [comment]
Hi @philippe101 I changed the title and description of this task somewhat so it has a more concrete deliverable (presentation of findings). I'm also putting it back in the ice box - please let me know if / when you'd like to present research findings at an upcoming hacknight.

Thanks!

**Comment by philippe101** [comment]
Hey @owenjoseph, I think we need to keep the comparative competitive research going until we have gathered all the elements spoken to all the parties and have started discussing the app structure or at least have a better understanding of the app we want to build.

Diana said she contacted Lease Up and wanted to arrange a follow up call with the founder and I think we should do that. We should try to talk to as many people as we can who have already gone down this path or thru a similar process of trying to match people among this community either in California or in other states. I don't think Diana is back until next week.

Let's discuss what is the right time and the right process to do all that. 

See ya tomorrow!

**Comment by owenjoseph** [comment]
Linking the Airtable Block @awadethomas created: https://airtable.com/invite/l?inviteId=invlwXeqEEm1ajfid&inviteToken=a1c4eeb74905f6c7aef6906ddb96601ae73c4bd9062c91347d99a47560a2eaa2

**Comment by owenjoseph** [comment]
And here's the "view" link that will be suitable to share with client stakeholders: https://airtable.com/shrn4XawKcG5Qh2YQ

Closing this as "Done"
