### ISSUE TITLE
Prepare questions for the Outreach/Engagement team

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#40]
### Overview
Elyssa & Alynn from the Outreach team are confirmed to come to DTLA hacknight on August 6th for an interview – we should prioritize reviewing questions for them!

### Action Items
- [x] link to Aaron's prepared questions
- [x] review / add questions during hacknight (July 16)

### Resources
Add link to prepared questions here

**Comment by awadethomas** [comment]
we don't technically have questions prepared yet, but some form of the following should work plus a few additional q's
https://hackmd.io/-F01ondTTJqgJWFhs4ypOA

**Comment by owenjoseph** [comment]
Calling this one done since @jlopez08 @AlexChh93 and @philippe101 are conducting the interview tonight.
