### ISSUE TITLE
Come up with a team name!

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#41]
### Overview
What, are we just gonna call ourselves LAFH-SH? That's not fun.

Aaron has proposed running a creative activity to come up with a team name. Let's do it!

**Comment by owenjoseph** [comment]
Here's the activity: https://www.entrepreneur.com/article/223694

**Comment by awadethomas** [comment]
Let's make it a point to get through this on Tuesday!

**Comment by awadethomas** [comment]
Welp, we started this exercise but couldn't get through it in time. It seemed to be fruitful to get the juices flowing.

**Comment by c-fuchs** [comment]
"Shared Housing" seems to have stuck, though we do have a fun name for the SMILE app.
