### ISSUE TITLE
Create generic form input component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#45]
### Overview
Create a generic form input component.

### Action Items
The component will need the following:
- [x] onChange handler
- [x] Label property
- [x] Value property
- [ ] Validation compliant (Yup wrapper)
- [x] Controlled component
- [x] Using Material-UI TextField component
- [ ] Accessibility compliance (A11y standard)

### Resources/Instructions
- [Material-UI Text Field component](https://material-ui.com/components/text-fields)

**Comment by itsevalieu** [comment]
@abregorivas  Hey Roland, I started on this generic form input component last week, but I think you've already taken care of it with the BaseInput component. Shall I simple mark this as complete or reassign to you?

**Comment by abregorivas** [comment]
I will assign it to myself. I may need to add a modification.
