### ISSUE TITLE
Create generic form switch component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#48]
### Overview
Create a generic form switch component.

### Action Items
The component will need the following:
- [ ] onChange handler
- [ ] Label property
- [ ] Value property
- [ ] Validation compliant (Yup wrapper)
- [ ] Controlled component
- [ ] Using Material-UI Switch component
- [ ] Accessibility compliance (A11y standard)

### Resources/Instructions
- [Material-UI Switch component](https://material-ui.com/components/switches)

**Comment by karlmageddon** [comment]
I'd like to tackle this
