### ISSUE TITLE
Create generic form button component

### ISSUE THREAD

**Issue by tabatahg** [hackforla/shared-housing#49]
Overview
Create a generic form button component

Action Items
- [ ] onClick handler
- [ ] Label property
- [ ] Value property
- [ ] Validation compliant (Yup wrapper)
- [ ] Controlled component
- [ ] Using Material-UI button component
- [ ] Accessibility compliance (A11y standard)
- [ ] Option to disable

Resources/Instructions
https://material-ui.com/components/buttons/

**Comment by kkchu791** [comment]
I'd be interested to take this one

**Comment by kkchu791** [comment]
After reading the docs for material UI, i think the material UI button component will be reusable enough for all scenarios I can think of for our app. 

At first I thought it didn't handle for icon placement on the button (can we have the icon go on the left of the button text in some cases, and also to the right in others.) So I wrote out a baseButton component.

`import React from 'react';
import PropTypes from 'prop-types';
import Button from '@material-ui/core/Button';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const renderButtonContent = (buttonText, icon, iconSide) => {
  if (iconSide === 'left') {
    return (
      <div>
        <FontAwesomeIcon icon={icon} /> {buttonText}
      </div>
    )
  } else {
    return (
      <div>
        {buttonText} <FontAwesomeIcon icon={icon} />
      </div>
    )
  }
}

export const BaseButton = ({
  buttonText,
  className,
  color,
  onClick,
  icon,
  iconSide,
  size,
  variant,
}) => {
  return (
    <Button
      classes={className}
      color={color}
      onClick={onClick}
      size={size}
      variant={variant}
    >
      {renderButtonContent(buttonText, icon, iconSide)}
    </Button>
  )
}
`

But after reading these docs https://material-ui.com/components/buttons/#buttons-with-icons-and-label, I feel material UI covers it.
