### ISSUE TITLE
Create a generic form date/time picker component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#50]
### Overview
Create a generic form date/time picker component.

### Action Items
The component will need the following:
- [ ] Date type (mandatory)
- [ ] Time type (pending)
- [ ] onChange handler
- [ ] Label property
- [ ] Value property
- [ ] Validation compliant (Yup wrapper)
- [ ] Controlled component
- [ ] Using Material-UI Date/Time Picker component
- [ ] Accessibility compliance (A11y standard)

### Resources/Instructions
- [Material-UI Picker component](https://material-ui.com/components/pickers)

**Comment by tabatahg** [comment]
I would like to tackle this issue.
