### ISSUE TITLE
Create Generic Dropdown Component

### ISSUE THREAD

**Issue by abregorivas** [hackforla/shared-housing#51]
### Overview
Create a generic form input component.

### Action Items
The component will need the following:
- [ ] onSelect/onChange handler
- [ ] Label property
- [ ] Value should be an array of items
- [ ] Validation compliant (Yup wrapper)
- [ ] Controlled component
- [ ] Using Material-UI TextField component
- [ ] Accessibility compliance (A11y standard)

### Resources/Instructions
- [Material-UI Text Field component](https://material-ui.com/components/text-fields)

**Comment by wsbuck** [comment]
I would like to work on this.
