### ISSUE TITLE
Plot out LAFH service map (w/r/t shared housing)

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#56]
### Overview
To get a better sense of the overall process, and to make sure we're understanding the current reality of that process, we'd like to create a service map of the current shared housing efforts from LAFH's perspective. I.e. not a user journey, per se, but a map of all team's involvement in the process of assembling groups, sourcing housing, and getting those groups into housing.

### Action Items
- [x] review the interviews we've conducted so far w/ Location and Stabilization teams
- [x] start document

### Resources
Link to shared housing interview artifacts: https://drive.google.com/open?id=1vqR5xfPRvVpvk-fzNzGrjvKRwuR6BNOP

Link to service flowchart (PENDING)

**Comment by owenjoseph** [comment]
@Diquach I know we used a few different terms for what the product of this task would be – service map, service blueprint – I think what we're looking for is something that documents the full shared housing process from an organization standpoint, i.e. not a user journey. We're trying to capture how each team is involved in the process, where handoffs between teams are occurring, where communication / coordination needs to happen. Essentially: feel free to change the description of this issue!

**Comment by owenjoseph** [comment]
Potential activity to do at hack night: https://www.nngroup.com/articles/5-steps-service-blueprinting/

**Comment by Diquach** [comment]
@owenjoseph High level draft in progress.

**Comment by Diquach** [comment]
Link to WIP service map - https://miro.com/welcomeonboard/k4OV0EhlcW6RRLaTULkeKa0T8h4LzrX8LfsiCtGntYck5IAwurYRi2hSPUaiPFzz

**Comment by owenjoseph** [comment]
Link to Miro Board with User Journeys (Client and Navigator): https://miro.com/welcomeonboard/SIP4sS5eR2iGVyLJ9lGzNID6bPt03pLylOGWDPU3NCv5THEn98KUUacIDbyRAJdN

Link to Slide Deck describing User Journeys and Affinity Mapping Findings: https://docs.google.com/presentation/d/1FAxb6hUOxaURZxqHAPS5x5OZjUjJlPzr_XBt4TdcsW0/edit?usp=sharing
