### ISSUE TITLE
Follow up w/ Stabilization team re: client survey questions

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#58]
### Overview
This is follow-up based question on the interview we held with the team a few weeks ago. The Stabilization team has a survey it has its clients fill out regarding their experience in their shared housing. We'd like to review and archive a copy.

### Action Items
- [ ] reach back out to Stabilization team folks
- [ ] review survey for insights
- [ ] archive in Drive

### Resources
Drive link for client documents: https://drive.google.com/open?id=1Bfwmno49CDphQLhlk-jVomQwKNFQN7je

**Comment by awadethomas** [comment]
We're planning another meeting w/them soon - let's reach out about the questions then

**Comment by awadethomas** [comment]
We'll be chatting with Stabilization team members early this week, let's plan on collecting or reconnecting with them on these items then

**Comment by owenjoseph** [comment]
@awadethomas did you have a chance to follow up with stabilization on these items?

**Comment by awadethomas** [comment]
I did follow up twice now to no avail. I can try once more if we're able to speak with any other members of the team.

**Comment by awadethomas** [comment]
I just followed up for a third time

**Comment by owenjoseph** [comment]
This one's gone a bit stale. . . maybe we should bring this up with the Stabilization team again when we have a chance to do some immersive research w/ them.

**Comment by owenjoseph** [comment]
Folding this into #121
