### ISSUE TITLE
Migrate Project to TypeScript

### ISSUE THREAD

**Issue by brandonly101** [hackforla/shared-housing#68]
### Overview
Migrate Project from use of JavaScript to use of TypeScript.

### Action Items
- [x] Research how to enable TypeScript with the Parcel bundler.
- [x] Modify relevant config files
- [x] Refactor existing `*.js`/`*.jsx` files into `*.ts`/`*.tsx` files (optional)

### Resources/Instructions
* https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html (General page for migrating from vanilla JS to TS)
* https://parceljs.org/typeScript.html (Parcel documentation on using TypeScript with Parcel)

**Comment by tylerthome** [comment]
Let me know if I can lend a hand to whoever is taking this on. I'm on the back-end team for this project but have experience with React/TypeScript/Webpack/Babel and a lot of the idiosyncrasies when it comes to configuring the build pipeline

**Comment by ExperimentsInHonesty** [comment]
@brandonly101 you indicated this issue was partially addressed with pull request #129.  Can you indicate what remains on this issue?

**Comment by brandonly101** [comment]
@ExperimentsInHonesty Not much else other than actually converting the `*.js` and `*.jsx` files to `*.ts` and `*.tsx`. This step, however, is technically completely optional as development is still possible even if files are still `*.js` and `*.jsx` files.

We can start converting  `*.js` and `*.jsx` files to `*.ts` and `*.tsx`, if we choose so, to start using TypeScript. Files that are not yet converted will still be transpiled and thus be used as is.

**Comment by itsevalieu** [comment]
Closed, issue resolved with #129. Optional to convert to .ts/.tsx
