### ISSUE TITLE
Team Roster and Handles for access

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#8]
### Overview
Need everyone's slack and github handles for project materials access.

### Action Items
- [x] Create Sheet in shared H4LA Drive
- [x] Shoutout in Slack
- [x] Remind everyone at the Tuesday meeting
- [x] Skills Inventory

### Resources/Instructions
_Link to Sheet here when created._

**Comment by c-fuchs** [comment]
Link to team roster stored in [Wiki](https://github.com/hackforla/shared-housing/wiki/People-Involved).
