### ISSUE TITLE
Create a generic Button component

### ISSUE THREAD

**Issue by itsevalieu** [hackforla/shared-housing#81]
### Overview
Create a generic Button component using Material UI. 

### Action Items
- [ ] Add the component to Storybook
- [ ] Be able to accept props
- [ ] Add in different Buttons components (Submit, Delete, etc)

### Resources/Instructions
[Material UI Button](https://material-ui.com/components/buttons/)

**Comment by catmclough** [comment]
I can do this one!

**Comment by catmclough** [comment]
This one was done here: https://github.com/hackforla/shared-housing/pull/102
