### ISSUE TITLE
Milestone 1 - Discovery Phase (1/2)

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#85]
## Milestone Goal
Gain a high level understanding of the organization, efforts for shared housing, who else occupies the space, etc…
### Client Deliverables
- [x] Project Milestones (Initial)
- [x] Scope
  - [x] Scope Document
  - [ ] Scope Signoff
- [ ] Service Map
  - [ ] Service Map Signoff
- [ ] C&C Analysis

#### Stakeholder Interviews (Informational)
- [x] Location
- [x] Navigation
- [x] Stabilization
- [x] Location

**Comment by awadethomas** [comment]
@owenjoseph this looks great! I added a bit to the scope doc and I think the milestones doc is nearly set for what we can foresee.

**Comment by owenjoseph** [comment]
I'm going to close this issue since we're tacking using the actual milestones – I think this is redundant
