### ISSUE TITLE
Scope Document

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/shared-housing#86]
### Overview
As part of our first Milestone client deliverables, and in order to ensure LAFH continues to be invested in our project efforts, we will produce a Scope of Work document for their review and sign-off.

At a very high level, this document should describe the project goals, the steps taken so far, the steps we plan to take still, and set expectations for both the client and our team.

### Action Items
- [x] Assemble Outline incorporating results of brainstorming session from 8/6 (see pics attached)
- [x] Complete sections
- [x] Incorporate Feedback
- [x] get project lead sign-off
- [x] get client signoff

### References
WIP Scope Document (deprecated): https://docs.google.com/document/d/1vz6v9AH8tHmtJBWV5me3JxODuenaEJTVzYYhejGAuD4/edit?usp=sharing
Current Document ("Project Brief"): https://docs.google.com/document/d/1ZfGLq2YTR6Q65o0BEllcvkU0LFpnkQRWRgpEYigUX6w/edit?usp=sharing

**Comment by awadethomas** [comment]
I added a bit to the doc, but we still need to add the skeleton we drafted up on the whiteboard at our last session

**Comment by owenjoseph** [comment]
Adding snaps of whiteboard brainstorming here, for posterity.

![IMG_1703](https://user-images.githubusercontent.com/39287217/62981520-47698d80-bdde-11e9-9ab2-7adbf247b831.png)

**Comment by owenjoseph** [comment]
Presented this to Dan and Kris last week and got both of their buy-in (no one signed anything 😄 ). Closing this as successful (though we will continue to refine and add to the document as the project progresses).
